h1_oro_multi_savepay_callback:
    resource:     "@H1OroMultiSafepayBundle/Controller/CallbackController.php"
    type:         annotation
    prefix:       /multi-savepay/callback
    options:
        frontend: true
