h1_oro_multi_safepay_callback:
    resource:     "@H1OroMultiSafepayBundle/Controller/CallbackController.php"
    type:         annotation
    prefix:       /multi-safepay/callback
    options:
        frontend: true
